"""Persistence contract using workout records, without storage keys or expressions."""
from typing import Any, Mapping, Optional, Protocol

Record = Mapping[str, Any]


class WorkoutIdentity(Protocol):
    user_id: str

    @property
    def pk(self) -> str: ...


class WorkoutRepository(Protocol):
    """Mutations are atomic and reject changed parent/child revisions with WorkoutConflict.

    Session/execution records contain application fields only. Set lists retain
    legacy public metadata fields; callers pass those through without interpreting them.
    Reads must observe prior
    successful writes; multiple reads do not promise a single atomic snapshot.
    """

    def get_active_session(self, identity: WorkoutIdentity) -> tuple[bool, Optional[dict[str, Any]]]:
        """Return pointer existence and its session, retaining dangling-pointer detection."""
        ...

    def get_session(self, identity: WorkoutIdentity, session_id: str) -> Optional[dict[str, Any]]: ...
    def get_executions(self, identity: WorkoutIdentity, session: Record) -> list[dict[str, Any]]: ...
    def get_execution(self, identity: WorkoutIdentity, session: Record, execution_id: str) -> Optional[dict[str, Any]]: ...
    def get_sets(self, identity: WorkoutIdentity, session: Record, execution: Record) -> list[dict[str, Any]]: ...
    def get_set(self, identity: WorkoutIdentity, session: Record, execution: Record, ordinal: int) -> Optional[dict[str, Any]]: ...
    def list_history(self, identity: WorkoutIdentity, *, limit: Any = 20, cursor: Optional[str] = None) -> dict[str, Any]: ...
    def create_session(self, identity: WorkoutIdentity, session: Record, executions: list[dict[str, Any]]) -> None: ...
    def update_execution(self, identity: WorkoutIdentity, session: Record, execution: Record, fields: Record, expected: int, *, selectable: bool = False) -> None: ...
    def save_set(self, identity: WorkoutIdentity, session: Record, execution: Record, item: Record, expected_set: int, execution_expected: int, exists: bool) -> None: ...
    def complete_session(self, identity: WorkoutIdentity, session: Record, executions: list[dict[str, Any]], expected: int, now: str) -> None: ...
    def cancel_session(self, identity: WorkoutIdentity, session: Record, expected: int, now: str) -> None: ...
